services:
  postgres:
    image: postgres:latest
    container_name: task_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    restart: unless-stopped
